### ISSUE TITLE
12975 TDA Telecoms [bulk resume upload]

### ISSUE THREAD

**Issue by mbothner** [team-loxo/summernote-at-mention#26]

**Comment by mbothner** [comment]
Uploaded bulk resumes to FTP - can we please confirm we received them? Additionally, can you let me know how many resumes were added so that I can charge the customer accordingly?

**Also - the customer would like all of these resumes added to a list as well - Riggers List**

**Comment by prnie** [comment]
@icheishvili is there any reason that you closed this card?

**Comment by icheishvili** [comment]
@prnie this repo is a public repo: https://github.com/team-loxo/summernote-at-mention

**Comment by prnie** [comment]
@icheishvili oh I see. Thanks! 
@mbothner I'll re-create this ticket in the right repo.
