### ISSUE TITLE
Feature: configurable @-trigger character

### ISSUE THREAD

**Issue by micdobro** [team-loxo/summernote-at-mention#9]
Firstly - I am happy I found your plugin :) I have quickly skimmed through the code and I can see, that the `@` trigger-character could be actually made into a configurable option. 

My plan is actually to "misuse" the plugin and use it as a variable autocomplete help system - and obviously I would like to select a different character that will clearly separate raw text from a variable that later will be string-replaced automatically. 

It would be best to keep the contribution at the source (otherwise I will have to fork) - is that something that falls within the scope of the project - or should I fork?

**Comment by seangarita** [comment]
Hi there! I definitely think a configurable trigger-character would make sense for the project (with a default to the `@` symbol).

**Comment by micdobro** [comment]
Great. I will then make sure it gets there. I have planned summernote integration for this week - so expect a PR within the coming 14 days. I have also some other ideas - but if I end up implementing them I will open new issues and group these as separate PRs.

**Comment by seangarita** [comment]
Glad to hear it. I look forward to your PR.
